# Generated by Django 4.2.2 on 2023-12-25 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_member_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='category',
            field=models.ManyToManyField(blank=True, related_name='articles', to='blog.category', verbose_name='دسته بندی ها'),
        ),
    ]
